# Generated by Django 4.1.2 on 2022-10-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.CharField(default='ziqzed', max_length=200),
            preserve_default=False,
        ),
    ]
